.github/workflows/docs-deploy.yml

What: Updated docs deploy workflow

feat(docs): update docs deploy workflow

---

packages/documentation/components/table/table.doc.md
packages/documentation/components/tree/tree.doc.md
packages/ui/src/components/table/table.md
packages/ui/src/components/tree/tree.md

What:
How:
Link to Jira Ticket:
---

feat(docs): update docs demo paths

---

.github/workflows/docs-deploy.yml

What:
How:
Link to Jira Ticket:
---

feat(docs): build packages in docs workflow

---

packages/documentation/demos/typography/TypographyBasic.vue
packages/documentation/demos/typography/TypographyClasses.vue
packages/documentation/demos/typography/TypographyComponent.vue
packages/ui/src/components/typography/typography.ts
packages/ui/src/components/typography/typography.vue

Implemented typography component

feat(typography): implement typography component

---

packages/documentation/components/drawer/drawer.doc.md
packages/documentation/demos/__data__/data.mock.card.js
packages/documentation/demos/drawer/DrawerAnchor.vue
packages/documentation/demos/drawer/DrawerPersistent.vue
packages/documentation/demos/drawer/DrawerWidth.vue
packages/ui/src/components/card/card.spec.ts
packages/ui/src/components/card/card.ts
packages/ui/src/components/card/card.vue
packages/ui/src/components/drawer/drawer.css
packages/ui/src/components/drawer/drawer.md
packages/ui/src/components/drawer/drawer.spec.ts
packages/ui/src/components/drawer/drawer.ts
packages/ui/src/components/drawer/drawer.vue
packages/ui/src/composables/onClickSameTarget.ts
packages/ui/src/composables/useDOMScrollLock.ts
packages/ui/src/composables/useZIndex.ts
packages/ui/src/styles/tokens/acv/custom/transition.css
packages/ui/src/styles/utilities/index.css
packages/ui/src/styles/utilities/transitions.css
packages/ui/src/utils/vue.ts

feat(drawer): implement simple drawer

---

.github/workflows/visual-regression.yml

remove useless option in visual regression workflow

fix(test): remove useless option

---

packages/documentation/.vitepress/configuration/components.ts
packages/documentation/components/link/link.doc.md
packages/documentation/demos/link/LinkDisabled.vue
packages/documentation/demos/link/LinkHandlers.vue
packages/documentation/demos/link/LinkWithPath.vue
packages/ui/src/components/link/link.md
packages/ui/src/components/link/link.spec.ts
packages/ui/src/components/link/link.ts
packages/ui/src/components/link/link.vue
packages/ui/src/components/link/public.ts
packages/ui/src/components/ribbon/ribbon.vue

fix(link): implement basic link

---

packages/documentation/.vitepress/configuration/components.ts
packages/documentation/components/tooltip/tooltip.doc.md
packages/documentation/demos/utilities/TextMiddleEllipsis.vue
packages/ui/src/components/popper/popper.vue
packages/ui/src/components/tooltip/tooltip.md
packages/ui/src/directives/specs/highlight.spec.ts
packages/ui/src/directives/specs/textMiddleEllipsis.spec.ts
packages/ui/src/directives/specs/tooltipDirective.spec.ts
packages/ui/src/directives/textMiddleEllipsis.ts
packages/ui/vitest.config.ts

fix(tooltip): implement basic tooltip

---

package.json

Prevent test watch when run root test script

chore:  prevent test watch when run root test script

---

package.json
packages/configs/package.json
packages/documentation/demos/markup-table/MarkupTableSimple.vue
packages/icons/bin/utils/getCollections.ts
packages/ui/src/components/icon-button/iconButton.ts
packages/ui/src/components/markup-table/composables/useTableState.ts
packages/ui/src/components/markup-table/utils/jsonParseSafe.js
packages/ui/src/components/popper/popper.vue
packages/ui/src/composables/useBreakpoints.ts
packages/ui/src/utils/color.ts
packages/ui/src/utils/props.ts
packages/utils/src/object.ts
pnpm-lock.yaml

chore(lint): fix eslint errors

---

packages/documentation/components/accordion/accordion.doc.md
packages/documentation/components/breadcrumbs/breadcrumbs.doc.md
packages/documentation/components/button-group/buttonGroup.doc.md
packages/documentation/components/button/button.doc.md
packages/documentation/components/cell/cell.doc.md
packages/documentation/components/checkbox/checkbox.doc.md
packages/documentation/components/container/container.doc.md
packages/documentation/components/dialog/dialog.doc.md
packages/documentation/components/divider/divider.doc.md
packages/documentation/components/grid/grid.doc.md
packages/documentation/components/header/header.doc.md
packages/documentation/components/icon-button/iconButton.doc.md
packages/documentation/components/icon/icon.doc.md
packages/documentation/components/input/input.doc.md
packages/documentation/components/popover/popover.doc.md
packages/documentation/components/popper/popper.doc.md
packages/documentation/components/ribbon/ribbon.doc.md
packages/documentation/components/row/row.doc.md
packages/documentation/components/tooltip/tooltip.doc.md
packages/ui/src/components/accordion/accordion.ts
packages/ui/src/components/button-group/buttonGroup.ts

chore(docs): update generated docs

---

packages/documentation/.vitepress/configuration/examples.ts
packages/documentation/components/button/button.doc.md
packages/documentation/demos/button/ButtonColorDanger.vue
packages/documentation/demos/button/ButtonColorInfo.vue
packages/documentation/demos/button/ButtonColorInverted.vue
packages/documentation/demos/button/ButtonColorSuccess.vue
packages/documentation/demos/button/ButtonColorWarning.vue
packages/documentation/demos/button/ButtonDocSizes.vue
packages/documentation/demos/button/ButtonDocStates.vue
packages/documentation/demos/button/ButtonDocTypes.vue
packages/documentation/demos/button/ButtonDocWithIcons.vue
packages/documentation/examples/button.md
packages/documentation/examples/button/colors.md
packages/documentation/examples/button/pill.md
packages/documentation/examples/button/sizes.md
packages/documentation/examples/button/squared.md
packages/documentation/examples/button/types.md
packages/documentation/examples/button/variants.md
packages/ui/src/components/button/button.md
packages/ui/src/components/button/button.ts
packages/ui/src/components/button/button.vue
packages/ui/src/components/confirm-dialog/confirmDialog.spec.ts
packages/ui/src/components/icon-button/iconButton.spec.ts

fix(button): fix button types

---

packages/documentation/demos/icon-internal/IconAcronis.vue
packages/documentation/theming/icons.md

docs(icons): update icons list

---

packages/documentation/components/list/list.doc.md

Please include a summary of the change and which issue is fixed. 
Please also include relevant motivation and context. 
List any dependencies that are required for this change.
Please describe the tests that you ran to verify your changes. 
Provide instructions so we can reproduce. 
Please also list any relevant details for your test configuration
_We encourage you to keep the code coverage percentage at 80% and above._
have not been included_
Please replace this line with instructions on how to test your changes,
a note on the devices and browsers this has been tested on, 
as well as any relevant images for UI changes.
_If your PR includes UI changes, please utilize this checklist:_

chore(list): fix dead links

---

packages/documentation/components/icon/icon.md
packages/ui/src/components/icon/icon.spec.ts
packages/ui/src/components/icon/icon.ts
packages/ui/src/components/icon/icon.vue

fix: remove dynamic icons

---

package.json
packages/ui/tsconfig.json
pnpm-lock.yaml

chore: update pnpm

---

packages/ui/src/styles/tokens/acronis.css
packages/ui/src/styles/tokens/base.css
packages/ui/src/styles/tokens/constructor.css
packages/ui/src/styles/tokens/virtuozzo.css

style: update figma tokens

---

packages/ui/src/components/card/card.vue
packages/ui/src/components/popover/popover.vue

fix: apply background in popover

---

packages/icons/public/IconDot16.svg
packages/icons/public/IconDotWidget16.svg
packages/icons/public/dot.d.ts
packages/icons/public/dot.js
packages/icons/vue/IconDot16.d.ts
packages/icons/vue/IconDot16.js

feat: add dot icon

---

.github/workflows/docs-deploy.yml
packages/ui/.gitignore

Build storybook in Docs deploy Github action

build: build storybook in Docs deploy Github action

---

packages/ui/src/components/dialog/dialog.css

fix(dialog): add xx-large dialog width

---

packages/documentation/components/pagination/AcvPaginationItem.md
packages/ui/src/components/pagination/AcvPaginationItem.vue

The documentation generator doesn't seem to be able to access the files by aliases

fix(pagination): replace the import path with a relative path

---

.github/workflows/ci.yml

cache pnpm dependencies in ci workflow

build: cache pnpm dependencies in ci workflow

---

.github/workflows/utils-npm-publish.yml
.github/workflows/utils-release.yml
packages/utils/package.json

build: publish utils npm package

---

packages/ui/src/components/card/card.css
packages/ui/src/components/card/card.spec.ts
packages/ui/src/components/card/card.stories.ts
packages/ui/src/components/card/card.ts
packages/ui/src/components/card/card.vue
packages/ui/src/components/drawer/drawer.spec.ts
packages/ui/src/components/popover/popover.vue

feat: update Card component

---

packages/ui/src/index.ts
packages/ui/src/utils/util.ts
packages/utils/src/index.ts
packages/utils/src/isArray.ts
packages/utils/src/isObjectLike.ts

Allowed to add the library to Vue 3 application as the plugin
–

fix(ui): allowed to add the library to Vue 3 application as the plugin

---

packages/documentation/components/button/button.doc.md

- [ x ] Documentation (updates to the documentation, readme or JSDoc annotations)
Improve docs so it will be easier for designer to see our button component examples better and some other minor changes.

refactor: improve button docs

---

packages/ui/src/index.ts

Fixed typings of Vue plugin installer function
–
–

fix(ui): fixed typings of Vue plugin installer function

---

packages/documentation/.gitignore
packages/documentation/.vitepress/config.ts
packages/documentation/.vitepress/configuration/components.ts
packages/documentation/.vitepress/configuration/examples.ts
packages/documentation/.vitepress/configuration/vite.ts
packages/documentation/.vitepress/utils.ts
packages/documentation/examples/[pkg]-[demo].md
packages/documentation/examples/[pkg]-[demo].paths.js
packages/documentation/examples/[pkg].paths.js
packages/documentation/package.json
packages/examples/__mocks__/data.mock.classes.js
packages/examples/demos/docs/ColorCharts.vue
packages/examples/demos/form/FormAlwaysError.vue
packages/examples/demos/form/FormValidationStatus.vue
packages/examples/demos/pagination/PaginationWithRouter.vue
packages/examples/demos/popover/PopoverReference.vue
packages/examples/demos/table/TableColumns.vue
packages/examples/demos/theme/theme.vue
packages/examples/demos/widget-wrapper/WidgetWrapperWithHeaderAndFooter.vue
pnpm-lock.yaml

Fix failed build in documentation package

fix(docs): fix production build in documentation

---

packages/examples/demos/button/ButtonDoc.vue
packages/examples/demos/button/ButtonDocSizes.vue
packages/examples/demos/button/ButtonDocWithIcons.vue
packages/examples/demos/button/ButtonWithLoading.vue
packages/examples/demos/button/ButtonWithSingleIcon.vue

- [ x ] Documentation (updates to the documentation, readme or JSDoc annotations)
- [ x ] Bug fix (a non-breaking change that fixes an issue)
- [ x ] Refactoring (old API is revised and supported)
This fixes issue with seeing translucent buttons incorrectly and some additional style fixes

fix: button doc components broken styles

---

packages/figma-fetcher/src/downloadChunks.js
packages/figma-fetcher/src/getFigmaIcons.js

Improve logs for figma fetcher

feat: improve icons logs

---

packages/figma-fetcher/src/helpers.js

Ability to pass token with env

fix: pass figma token with env

---

packages/figma-fetcher/src/helpers.js

Allow passing multiple frames and validate icon names across the entire group instead of per-frame.

fix: name normalizer should cover cases with names like "Long  Name" and "long-name"

---

packages/figma-fetcher/src/downloadIcons.js
packages/figma-fetcher/src/downloadImage.js

Improved the display of broken icons — they are now more visibly marked or styled, making it easier for developers and users to identify missing or failed icons. This change helps with debugging and ensures better visual feedback when icons fail to load or are misconfigured.

fix(ui): improve clarity of broken icon display

---

packages/figma-fetcher/index.js
packages/figma-fetcher/src/downloadImage.js

this image without prefix, but with prefix it solve your problem, and fix issue

fix: the icon prefix should be the same, otherwise, links to fills
